"use client";
import { useEffect, useRef, useState } from "react";
type Theme = "naruto" | "sasuke";
const projects=[
{no:"01",title:"Multi-Document RAG",type:"AI / KNOWLEDGE",text:"Grounded answers across many documents through retrieval, ranking, and context-aware generation.",tech:"Python · RAG · Vector Search · LLMs",url:"https://github.com/Koushikroyal2005?tab=repositories&q=rag"},
{no:"02",title:"Trading Agent",type:"AGENTIC AI / FINTECH",text:"An autonomous workflow for market research, signal evaluation, and guarded decision support.",tech:"Python · Agents · Market Data · Automation",url:"https://github.com/Koushikroyal2005?tab=repositories&q=trading"},
{no:"03",title:"OEguard",type:"VISION / SAFETY",text:"A child screen-time guardian with gaze detection, personalized warnings, anti-cheat logic, and parent alerts.",tech:"OpenCV · MediaPipe · Gemini · ChromaDB",url:"https://github.com/Koushikroyal2005/OEguard"},
{no:"04",title:"Personal Calorie Tracker",type:"AI / HEALTH",text:"A focused nutrition companion for daily logging, useful summaries, and progress awareness.",tech:"Full Stack · AI · Analytics · UX",url:"https://github.com/Koushikroyal2005?tab=repositories&q=calorie"},
{no:"05",title:"CodeOrbit",type:"FULL STACK / DEVTOOLS",text:"Live Codeforces analytics, 40+ tag problem discovery, bookmarks, and cached daily challenges.",tech:"React · Node.js · MongoDB · Codeforces API",url:"https://github.com/Koushikroyal2005/code_orbit",live:"https://code-orbit-scj0.onrender.com"},
{no:"06",title:"SynapseMesh",type:"WEB3 / AI INFRA",text:"Trustless agent coordination with onchain task DAGs, TEE verification, and atomic settlement on 0G.",tech:"React · Solidity · Ethers · Python",url:"https://github.com/Koushikroyal2005?tab=repositories&q=SynapseMesh",live:"https://synapsemesh.vercel.app"}];
const certs=[
["01","Amazon","Machine Learning Summer School","Top 3% participant · 2025"],["02","Google","Cybersecurity Professional Certificate","Security foundations & operations"],["03","Google","Gemini for Developers","Generative AI development"],["04","Google","Code Vipassana: AI Agents","Agentic systems workshop"],["05","Stanford / Coursera","Machine Learning Specialization","Supervised & unsupervised learning"],["06","IBM","Linux Commands & Shell Scripting","Command line and automation"],["07","Udemy","Full-Stack Web Development","Modern web application development"]];
export default function Home(){
const[theme,setTheme]=useState<Theme>("naruto"),[ready,setReady]=useState(false),[switching,setSwitching]=useState(false);
const portraitRef=useRef<HTMLDivElement>(null),cursorRef=useRef<HTMLDivElement>(null),dark=theme==="sasuke";
useEffect(()=>{const saved=localStorage.getItem("portfolio-theme");setTheme(saved==="sasuke"?"sasuke":"naruto");const timer=setTimeout(()=>setReady(true),900);
const move=(e:PointerEvent)=>cursorRef.current?.style.setProperty("transform",`translate3d(${e.clientX}px,${e.clientY}px,0)`);
const scroll=()=>document.documentElement.style.setProperty("--progress",String(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)));
addEventListener("pointermove",move);addEventListener("scroll",scroll,{passive:true});const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("in-view")),{threshold:.14});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
return()=>{clearTimeout(timer);removeEventListener("pointermove",move);removeEventListener("scroll",scroll);observer.disconnect()}},[]);
useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("portfolio-theme",theme)},[theme]);
const changeTheme=(next:Theme)=>{if(next===theme)return;setSwitching(true);setTimeout(()=>setTheme(next),260);setTimeout(()=>setSwitching(false),820)};
const portraitMove=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;portraitRef.current?.style.setProperty("--mx",`${x}%`);portraitRef.current?.style.setProperty("--my",`${y}%`);portraitRef.current?.style.setProperty("--tilt-x",`${(50-y)*.07}deg`);portraitRef.current?.style.setProperty("--tilt-y",`${(x-50)*.09}deg`)};
return <main className={`site ${ready?"ready":""}`}>
<div className="intro"><div className="intro-seal">{dark?"雷":"火"}</div><span>ENTERING THE HIDDEN CODE VILLAGE</span></div>
<div className={`theme-wipe ${switching?"active":""}`}><span>{dark?"火":"雷"}</span></div><div className="noise"/><div className="scroll-progress"/><div className="chakra-cursor" ref={cursorRef}><i/><b/></div><div className="beast-mark">{dark?"須":"九"}</div>
<header className="topbar"><a href="#home" className="logo"><b>{dark?"雷":"火"}</b><span>KOUSHIK<br/>KOTTE</span></a><nav><a href="#missions">Missions</a><a href="#journey">Journey</a><a href="#scrolls">Scrolls</a><a href="#contact">Contact</a></nav><div className="mode-switch" aria-label="Choose portfolio theme"><button className={!dark?"selected":""} onClick={()=>changeTheme("naruto")} aria-label="Switch to Naruto light mode">N</button><button className={dark?"selected":""} onClick={()=>changeTheme("sasuke")} aria-label="Switch to Sasuke dark mode">S</button></div></header>
<section className="hero-scene" id="home"><div className="hero-grid"><div className="hero-text"><div className="micro-label"><i/> {dark?"THE PATH OF LIGHTNING":"THE WILL OF FIRE"} · PORTFOLIO 2026</div><h1><span>KOUSHIK</span><strong>KOTTE</strong></h1><div className="hero-role"><span>AI ENGINEER</span><i/><span>FULL-STACK DEVELOPER</span></div><p>I build intelligent products and production systems that stay fast, observable, and useful when the real world gets messy.</p><div className="hero-actions"><a href="#missions" className="cta"><span>VIEW MY MISSIONS</span><b>↗</b></a><a href="/Koushik-Kotte-Resume.pdf" className="resume-link" download>RÉSUMÉ <span>↓</span></a></div></div>
<div className="portrait-world"><div className="chakra-ring ring-a"/><div className="chakra-ring ring-b"/><div className="beast-name">{dark?"SUSANOO":"KURAMA"}</div><div className="portrait-stage" ref={portraitRef} onPointerMove={portraitMove} onPointerLeave={()=>{portraitRef.current?.style.setProperty("--tilt-x","0deg");portraitRef.current?.style.setProperty("--tilt-y","0deg")}}><img src="/assets/koushik-pose-v2.png" alt="Koushik Kotte"/><div className="portrait-reveal"/><div className="lens-outline"/><span className="portrait-tip">MOVE CURSOR TO REVEAL {dark?"SASUKE":"NARUTO"}</span></div><div className="floating-card rank-card"><span>CURRENT RANK</span><strong>{dark?"CHŪNIN":"GENIN+"}</strong></div><div className="floating-card location-card"><span>BASE</span><strong>NIT RAIPUR</strong></div></div></div>
<div className="stat-strip"><div><b>1,500+</b><span>DSA PROBLEMS</span></div><div><b>12×</b><span>LOGGING THROUGHPUT</span></div><div><b>70%</b><span>LESS MANUAL TESTING</span></div><div><b>8.51</b><span>CGPA / 10</span></div></div><div className="scroll-note">SCROLL TO BEGIN <i/></div></section>
<div className="jutsu-marquee"><div>{dark?"CHIDORI":"RASENGAN"} <b>✦</b> AGENTIC AI <b>✦</b> DISTRIBUTED SYSTEMS <b>✦</b> COMPUTER VISION <b>✦</b> OBSERVABILITY <b>✦</b> {dark?"AMATERASU":"RASEN SHURIKEN"} <b>✦</b> FULL-STACK ENGINEERING</div></div>
<section className="chapter" id="missions"><div className="chapter-index">CHAPTER 01</div><div className="chapter-head reveal"><div><span>SELECTED MISSIONS / 06</span><h2>Forged through<br/><em>real problems.</em></h2></div><p>Each mission began with uncertainty and ended as something people can use.</p></div><div className="missions">{projects.map((p,i)=><article className="mission reveal" key={p.title}><div className="mission-no">{p.no}</div><div className="mission-core"><span>{p.type}</span><h3>{p.title}</h3><p>{p.text}</p><small>{p.tech}</small></div><div className="mission-jutsu"><i/><i/><b>{i%2?(dark?"千":"螺"):(dark?"眼":"影")}</b></div><div className="mission-links"><a href={p.url} target="_blank">CODE ↗</a>{p.live&&<a href={p.live} target="_blank">LIVE ↗</a>}</div></article>)}</div></section>
<div className="scene-transition reveal"><div className="shuriken"><i/><i/><i/><i/><b/></div><span>{dark?"LIGHTNING CUTS THROUGH THE DARK":"WIND CARRIES THE FIRE FORWARD"}</span></div>
<section className="chapter" id="journey"><div className="chapter-index">CHAPTER 02</div><div className="chapter-head reveal"><div><span>FIELD EXPERIENCE</span><h2>Built under<br/><em>pressure.</em></h2></div><p>Short scroll. Real impact.</p></div><div className="ninja-scroll reveal"><div className="scroll-cap"/><div className="scroll-paper"><article><div className="date">JAN — JUN 2026</div><div><span>SDE INTERN</span><h3>Myntra · Flipkart Group</h3><p>Automation, fast logging, cache performance, and production observability.</p></div><div className="impact"><b>12×</b><small>LOGGING</small></div></article><article><div className="date">JUL — AUG 2026</div><div><span>AI EVALUATION SPECIALIST</span><h3>Handshake · Project Dynamo</h3><p>Debugging scenarios and rigorous evaluation of agent reasoning.</p></div><div className="impact"><b>20+</b><small>FAILURE MODES</small></div></article></div><div className="scroll-cap"/></div></section>
<section className="chapter arsenal" id="about"><div className="chapter-index">CHAPTER 03</div><div className="chapter-head reveal"><div><span>THE ARSENAL</span><h2>Chakra, translated<br/><em>into code.</em></h2></div></div><div className="arsenal-grid">{[["01","LANGUAGES","Java · Python · C++ · SQL · Bash"],["02","BACKEND","Spring Boot · Node.js · Express · REST · JPA"],["03","AI / DATA","Agentic AI · RAG · OpenCV · MediaPipe · Gemini"],["04","SYSTEMS","Kafka · Redis · MongoDB · PostgreSQL · MySQL"],["05","DEVOPS","Docker · Kubernetes · GitHub · CI/CD"],["06","OBSERVABILITY","Grafana · Prometheus · Elasticsearch · Log4j2"]].map(x=><div className="arsenal-item reveal" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><i/></div>)}</div></section>
<section className="chapter" id="scrolls"><div className="chapter-index">CHAPTER 04</div><div className="chapter-head reveal"><div><span>CERTIFICATION SCROLLS</span><h2>Proof of<br/><em>training.</em></h2></div><p>Continuous study across AI, security, Linux, and full-stack engineering.</p></div><div className="cert-track">{certs.map(c=><article className="cert-scroll reveal" key={c[0]}><div className="cert-seal">{c[0]}</div><span>{c[1]}</span><h3>{c[2]}</h3><p>{c[3]}</p><b>{dark?"蛇":"蛙"}</b></article>)}</div><div className="recognition reveal"><span>COMPETITIVE CODING</span><div><b>1854</b><small>LEETCODE KNIGHT · TOP 5%</small></div><div><b>1646</b><small>CODECHEF · 3 STAR</small></div><div><b>1320</b><small>CODEFORCES · PUPIL</small></div></div></section>
<section className="final-scene" id="contact"><div className="final-orb"><i/><i/><b>{dark?"雷":"螺"}</b></div><span>FINAL CHAPTER · BEGIN SOMETHING NEW</span><h2>Let&apos;s make the next<br/><em>legendary thing.</em></h2><p>Open to software engineering, AI engineering, and ambitious collaborations.</p><a href="mailto:kotte.koushik5021@gmail.com" className="mail-cta">START A CONVERSATION <b>↗</b></a><div className="social-row"><a href="https://github.com/Koushikroyal2005/" target="_blank">GITHUB</a><a href="https://www.linkedin.com/in/koushik-kotte/" target="_blank">LINKEDIN</a><a href="https://leetcode.com/u/I_Can_Do_This_AAll_Day/" target="_blank">LEETCODE</a><a href="https://codeforces.com/profile/kotte.koushik5021" target="_blank">CODEFORCES</a></div></section>
<footer><a href="#home" className="logo"><b>{dark?"雷":"火"}</b><span>KOUSHIK KOTTE</span></a><p>ENGINEERED WITH DISCIPLINE · 2026</p><a href="#home">RETURN TO TOP ↑</a></footer>
</main>}
